### ISSUE TITLE
Audacious Linux plugin crashing on Icebreaker(3DO) STR files

### ISSUE THREAD

**Issue by KynikossDragonn** [losnoco/vgmstream#148]
The vgmstream audacious plugin seems to have a horrible time trying to access these files.

(my username will be censored)

Trying to open the .STR results in this happening:
`ERROR vfs_local.cc:119 [fopen]: ~/tempshit/ice_002.STH: No such file or directory
Segmentation fault`

Renaming to .STH results in this happening:
`ERROR vfs_local.cc:119 [fopen]: ~/tempshit/ice_002.str: No such file or directory
ERROR vfs_local.cc:119 [fopen]: ~/tempshit/ice_002.str: No such file or directory
ERROR vfs_local.cc:119 [fopen]: ~/tempshit/ice_002.str: No such file or directory
ERROR vfs_local.cc:119 [fopen]: ~/tempshit/ice_002.STH.txth: No such file or directory
Segmentation fault`

Finally, renaming back to .STR and symlinking the file to .STH results in it finally playing but it sounds completely mono (the music is supposed to be in stereo)

Here's a screenshot of the file header if that helps:
![image](https://user-images.githubusercontent.com/8813106/33522060-bf0560a8-d7a8-11e7-8329-ae9e18b385a1.png)

**Comment by kode54** [comment]
This should be resolved by fecf28f0cfee050682da62784a355e9796db7bec, please recompile the plugin and test. Errors will still be thrown, but there should no longer be any crashes.

**Comment by KynikossDragonn** [comment]
Nolonger crashes anymore, still throws errors for not finding a STH file though. 

It also still reports being "stereo" but I only hear one channel of the song in both speakers so I presume it's still playing these files incorrectly.

**Comment by bnnm** [comment]
The stereo issue was fixed recently and I think I tweaked something to improve dual files, if you want to test again.

**Comment by awsms** [comment]
Looks like it's still not working here

**Comment by KynikossDragonn** [comment]
Only some of the files work properly now.

ice_001.STR returns a metadata error.
ice_011.STR plays a loud distorted sound for a fraction of a second.
ice_013.STR also plays a loud distorted sound for a fraction of a second.

But other than that everything else seems to play in stereo properly.

**Comment by bnnm** [comment]
ice_001.STR has no audio at all, others play fine for me. Maybe try to redownload the set or recompile (I tweaked minor things), and compare output vs test/vgmstream_cli? Or convert to wav with Audacious and post the file, could help to understand your issue.

**Comment by KynikossDragonn** [comment]
The archive submission hasn't been changed since 2013, and it's still the same exact files I have on hand when I downloaded this a while back.

The files that are supposed to play, play just fine so I guess just close the issue in this case and chalk up the problematic files being something else mistaken for music accidentally being included in the rip. (i.e. video data maybe)

**Comment by bnnm** [comment]
Bit rot is a real thing that has happened to me, so I would try a redownload just in case.

**Comment by bnnm** [comment]
Now that I was able to get Linux going, I tested some .STR and they were being captured and incorrectly played by mpg123 plugin. I tweaked stuff and I don't think it happens anymore, if you want to test again. 

If somehow they don't work try to disable mpg123 or other plugins + restart to find check it's a plugin issue.
