### ISSUE TITLE
Taiko no Tatsujin DS games' s14 music files not properly decoding by default

### ISSUE THREAD

**Issue by enderghast13** [losnoco/vgmstream#438]
The music files for "Taiko no Tatsujin DS: Touch de Dokodon!" and "Metcha! Taiko no Tatsujin DS: 7-tsu no Shima no Daibouken" (and maybe the 3rd DS game) are stored in .s14 files encoded with Siren 14 at 48 kbps. From experimenting with vgmstream, it seems to be that they are single-channel and have an interleave block size of 0x78. However, vgmstream seems to guess the interleave size incorrectly, causing the file to not be decoded properly. Renaming these files to "S037_b06.s14" solves the issue and allows them to be properly decoded. I can attach sample files and/or their decoded (wav) forms if needed.

Edit: After another test, it seems that "properly" decoded looping music files do not actually loop.

**Comment by bnnm** [comment]
Those s14 files are completely headerless, meaning there is no way to loop or detect how to play them 100% correctly. I could add filename detection if you post a list of names<>interleaves, but it's a quite horrid way to support those files.

DS games with s14 I checked had the header info directly within code (as a switch list of "name1.s14: loop X/Y, sample rate Z, etc". Normally the way to support those cases is to create a .txthfile +name list to simulate/read the header (info [here](https://github.com/losnoco/vgmstream/blob/master/doc/TXTH.md)), but I haven't added siren14 yet.

**Comment by enderghast13** [comment]
Sorry for taking so long to get back. I'll try and give you a list of the games' s14 files later today. They all follow a specific pattern, but if you don't want to clutter the code too much by adding support for them, I totally understand. Thank you for your feedback :)

**Comment by enderghast13** [comment]
Here are the file trees for the games I mentioned (the first two DS games, three doesn't seem to use the same format) and data on the files. Let me know if you need anything else!
https://pastebin.com/A1kbzNER

**Comment by bnnm** [comment]
Fixed those files, not sure about looping tho.

**Comment by enderghast13** [comment]
I've tested and the files now decode properly with default names. Looping still doesn't work, as you've explained, but that seems out of the scope of this issue in my opinion, so I'm going to close this. Thank you, and sorry for the long wait!
